version: "3.9"
name: seattle-app
services:
  go-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mainekwok97/go-api
    ports:
      - "8081:8081"
    volumes:
      - "./backend/data:/app/data"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mainekwok97/seattle-frontend
    ports:
      - "3000:3000"
