version: "3.9"
services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mainekwok97/go-api
    ports:
      - "8081:8081"
    # env_file:
    #   - ../context/.env
    volumes:
      - "./data:/app/data"
